[general]
import = ["alacritty-themes/themes/material_theme.toml"]

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }

[window]
dimensions.columns = 120
dimensions.lines = 40

padding.x = 10
padding.y = 10

opacity = 0.9
blur = true
